// Mocks generated by Mockito 5.4.6 from annotations
// in open_plants/test/care_schedule_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i17;

import 'package:mockito/mockito.dart' as _i1;
import 'package:open_plants/pages/care_schedule/care_schedule_action.dart' as _i14;
import 'package:open_plants/pages/care_schedule/care_schedule_datasource.dart' as _i2;
import 'package:open_plants/pages/care_schedule/care_schedule_repository.dart' as _i9;
import 'package:open_plants/pages/care_schedule/care_task_type.dart' as _i15;
import 'package:open_plants/pages/care_schedule/custom_care_rule.dart' as _i13;
import 'package:open_plants/pages/care_schedule/room_config.dart' as _i11;
import 'package:open_plants/pages/care_schedule/schedule_config.dart' as _i3;
import 'package:open_plants/pages/care_schedule/species_care_profile.dart' as _i4;
import 'package:open_plants/pages/care_schedule/task_completion.dart' as _i12;
import 'package:open_plants/pages/plant_collection/plant_collection_item_entity.dart' as _i6;
import 'package:open_plants/pages/plant_collection/plant_collection_repository.dart' as _i5;
import 'package:open_plants/pages/plant_collection/plant_collection_usecases.dart' as _i16;
import 'package:open_plants/pages/plant_journal/plant_journal_item_entity.dart' as _i8;
import 'package:open_plants/pages/plant_journal/plant_journal_repository.dart' as _i7;
import 'package:open_plants/pages/plant_journal/plant_journal_usecases.dart' as _i18;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCareScheduleDataSource_0 extends _i1.SmartFake implements _i2.CareScheduleDataSource {
  _FakeCareScheduleDataSource_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeScheduleConfig_1 extends _i1.SmartFake implements _i3.ScheduleConfig {
  _FakeScheduleConfig_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSpeciesCareProfile_2 extends _i1.SmartFake implements _i4.SpeciesCareProfile {
  _FakeSpeciesCareProfile_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantCollectionRepository_3 extends _i1.SmartFake implements _i5.PlantCollectionRepository {
  _FakePlantCollectionRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantEntity_4 extends _i1.SmartFake implements _i6.PlantEntity {
  _FakePlantEntity_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantJournalRepository_5 extends _i1.SmartFake implements _i7.PlantJournalRepository {
  _FakePlantJournalRepository_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJournalEntry_6 extends _i1.SmartFake implements _i8.JournalEntry {
  _FakeJournalEntry_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CareScheduleRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCareScheduleRepository extends _i1.Mock implements _i9.CareScheduleRepository {
  MockCareScheduleRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.CareScheduleDataSource get dataSource => (super.noSuchMethod(
        Invocation.getter(#dataSource),
        returnValue: _FakeCareScheduleDataSource_0(
          this,
          Invocation.getter(#dataSource),
        ),
      ) as _i2.CareScheduleDataSource);

  @override
  _i10.Future<_i3.ScheduleConfig> getScheduleConfig(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getScheduleConfig,
          [plantId],
        ),
        returnValue: _i10.Future<_i3.ScheduleConfig>.value(_FakeScheduleConfig_1(
          this,
          Invocation.method(
            #getScheduleConfig,
            [plantId],
          ),
        )),
      ) as _i10.Future<_i3.ScheduleConfig>);

  @override
  _i10.Future<void> saveScheduleConfig(
    String? plantId,
    _i3.ScheduleConfig? config,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveScheduleConfig,
          [
            plantId,
            config,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, _i3.ScheduleConfig>> getAllScheduleConfigs() => (super.noSuchMethod(
        Invocation.method(
          #getAllScheduleConfigs,
          [],
        ),
        returnValue: _i10.Future<Map<String, _i3.ScheduleConfig>>.value(<String, _i3.ScheduleConfig>{}),
      ) as _i10.Future<Map<String, _i3.ScheduleConfig>>);

  @override
  _i10.Future<_i11.RoomConfig?> getRoomConfig(String? roomName) => (super.noSuchMethod(
        Invocation.method(
          #getRoomConfig,
          [roomName],
        ),
        returnValue: _i10.Future<_i11.RoomConfig?>.value(),
      ) as _i10.Future<_i11.RoomConfig?>);

  @override
  _i10.Future<void> saveRoomConfig(_i11.RoomConfig? config) => (super.noSuchMethod(
        Invocation.method(
          #saveRoomConfig,
          [config],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, _i11.RoomConfig>> getAllRoomConfigs() => (super.noSuchMethod(
        Invocation.method(
          #getAllRoomConfigs,
          [],
        ),
        returnValue: _i10.Future<Map<String, _i11.RoomConfig>>.value(<String, _i11.RoomConfig>{}),
      ) as _i10.Future<Map<String, _i11.RoomConfig>>);

  @override
  _i10.Future<List<_i12.TaskCompletion>> getAllCompletions() => (super.noSuchMethod(
        Invocation.method(
          #getAllCompletions,
          [],
        ),
        returnValue: _i10.Future<List<_i12.TaskCompletion>>.value(<_i12.TaskCompletion>[]),
      ) as _i10.Future<List<_i12.TaskCompletion>>);

  @override
  _i10.Future<List<_i12.TaskCompletion>> getCompletionsForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getCompletionsForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i12.TaskCompletion>>.value(<_i12.TaskCompletion>[]),
      ) as _i10.Future<List<_i12.TaskCompletion>>);

  @override
  _i10.Future<List<_i12.TaskCompletion>> getCompletionsForPlantAndType(
    String? plantId,
    String? taskTypeKey,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCompletionsForPlantAndType,
          [
            plantId,
            taskTypeKey,
          ],
        ),
        returnValue: _i10.Future<List<_i12.TaskCompletion>>.value(<_i12.TaskCompletion>[]),
      ) as _i10.Future<List<_i12.TaskCompletion>>);

  @override
  _i10.Future<void> recordCompletion(_i12.TaskCompletion? completion) => (super.noSuchMethod(
        Invocation.method(
          #recordCompletion,
          [completion],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteCompletion(_i12.TaskCompletion? completion) => (super.noSuchMethod(
        Invocation.method(
          #deleteCompletion,
          [completion],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, _i12.TaskCompletion>> getLatestCompletionsPerType(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getLatestCompletionsPerType,
          [plantId],
        ),
        returnValue: _i10.Future<Map<String, _i12.TaskCompletion>>.value(<String, _i12.TaskCompletion>{}),
      ) as _i10.Future<Map<String, _i12.TaskCompletion>>);

  @override
  _i10.Future<List<_i13.CustomCareRuleEntity>> getCustomCareRules(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getCustomCareRules,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i13.CustomCareRuleEntity>>.value(<_i13.CustomCareRuleEntity>[]),
      ) as _i10.Future<List<_i13.CustomCareRuleEntity>>);

  @override
  _i10.Future<List<_i13.CustomCareRuleEntity>> getAllCustomCareRules() => (super.noSuchMethod(
        Invocation.method(
          #getAllCustomCareRules,
          [],
        ),
        returnValue: _i10.Future<List<_i13.CustomCareRuleEntity>>.value(<_i13.CustomCareRuleEntity>[]),
      ) as _i10.Future<List<_i13.CustomCareRuleEntity>>);

  @override
  _i10.Future<void> saveCustomCareRule(_i13.CustomCareRuleEntity? rule) => (super.noSuchMethod(
        Invocation.method(
          #saveCustomCareRule,
          [rule],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteCustomCareRule(String? ruleId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomCareRule,
          [ruleId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i4.SpeciesCareProfile getSpeciesProfile(String? speciesId) => (super.noSuchMethod(
        Invocation.method(
          #getSpeciesProfile,
          [speciesId],
        ),
        returnValue: _FakeSpeciesCareProfile_2(
          this,
          Invocation.method(
            #getSpeciesProfile,
            [speciesId],
          ),
        ),
      ) as _i4.SpeciesCareProfile);

  @override
  _i10.Future<Map<String, _i14.CareScheduleAction>> getAllScheduleActions() => (super.noSuchMethod(
        Invocation.method(
          #getAllScheduleActions,
          [],
        ),
        returnValue: _i10.Future<Map<String, _i14.CareScheduleAction>>.value(<String, _i14.CareScheduleAction>{}),
      ) as _i10.Future<Map<String, _i14.CareScheduleAction>>);

  @override
  _i10.Future<_i14.CareScheduleAction?> getScheduleAction(
    String? plantId,
    _i15.CareTaskType? taskType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getScheduleAction,
          [
            plantId,
            taskType,
          ],
        ),
        returnValue: _i10.Future<_i14.CareScheduleAction?>.value(),
      ) as _i10.Future<_i14.CareScheduleAction?>);

  @override
  _i10.Future<void> saveScheduleAction(_i14.CareScheduleAction? action) => (super.noSuchMethod(
        Invocation.method(
          #saveScheduleAction,
          [action],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteScheduleAction(
    String? plantId,
    _i15.CareTaskType? taskType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteScheduleAction,
          [
            plantId,
            taskType,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAllScheduleActionsForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllScheduleActionsForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteCompletionsForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCompletionsForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteCustomRulesForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomRulesForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [PlantCollectionUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantCollectionUsecases extends _i1.Mock implements _i16.PlantCollectionUsecases {
  MockPlantCollectionUsecases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PlantCollectionRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePlantCollectionRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.PlantCollectionRepository);

  @override
  _i10.Future<List<_i6.PlantEntity>> loadPlants() => (super.noSuchMethod(
        Invocation.method(
          #loadPlants,
          [],
        ),
        returnValue: _i10.Future<List<_i6.PlantEntity>>.value(<_i6.PlantEntity>[]),
      ) as _i10.Future<List<_i6.PlantEntity>>);

  @override
  _i10.Future<_i6.PlantEntity?> getPlantById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getPlantById,
          [id],
        ),
        returnValue: _i10.Future<_i6.PlantEntity?>.value(),
      ) as _i10.Future<_i6.PlantEntity?>);

  @override
  _i10.Future<_i6.PlantEntity> addPlant(
    _i6.PlantEntity? plant, {
    _i17.File? photoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPlant,
          [plant],
          {#photoFile: photoFile},
        ),
        returnValue: _i10.Future<_i6.PlantEntity>.value(_FakePlantEntity_4(
          this,
          Invocation.method(
            #addPlant,
            [plant],
            {#photoFile: photoFile},
          ),
        )),
      ) as _i10.Future<_i6.PlantEntity>);

  @override
  _i10.Future<_i6.PlantEntity> updatePlant(
    _i6.PlantEntity? plant, {
    _i17.File? photoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePlant,
          [plant],
          {#photoFile: photoFile},
        ),
        returnValue: _i10.Future<_i6.PlantEntity>.value(_FakePlantEntity_4(
          this,
          Invocation.method(
            #updatePlant,
            [plant],
            {#photoFile: photoFile},
          ),
        )),
      ) as _i10.Future<_i6.PlantEntity>);

  @override
  _i10.Future<void> deletePlant(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlant,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i6.PlantEntity>> searchPlants(String? query) => (super.noSuchMethod(
        Invocation.method(
          #searchPlants,
          [query],
        ),
        returnValue: _i10.Future<List<_i6.PlantEntity>>.value(<_i6.PlantEntity>[]),
      ) as _i10.Future<List<_i6.PlantEntity>>);

  @override
  _i10.Future<List<_i6.PlantEntity>> filterByCareStatus(_i6.CareStatus? status) => (super.noSuchMethod(
        Invocation.method(
          #filterByCareStatus,
          [status],
        ),
        returnValue: _i10.Future<List<_i6.PlantEntity>>.value(<_i6.PlantEntity>[]),
      ) as _i10.Future<List<_i6.PlantEntity>>);

  @override
  _i10.Future<_i6.PlantEntity> markAsWatered(_i6.PlantEntity? plant) => (super.noSuchMethod(
        Invocation.method(
          #markAsWatered,
          [plant],
        ),
        returnValue: _i10.Future<_i6.PlantEntity>.value(_FakePlantEntity_4(
          this,
          Invocation.method(
            #markAsWatered,
            [plant],
          ),
        )),
      ) as _i10.Future<_i6.PlantEntity>);

  @override
  _i10.Future<_i6.PlantEntity> markAsFertilized(_i6.PlantEntity? plant) => (super.noSuchMethod(
        Invocation.method(
          #markAsFertilized,
          [plant],
        ),
        returnValue: _i10.Future<_i6.PlantEntity>.value(_FakePlantEntity_4(
          this,
          Invocation.method(
            #markAsFertilized,
            [plant],
          ),
        )),
      ) as _i10.Future<_i6.PlantEntity>);
}

/// A class which mocks [PlantJournalUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantJournalUseCases extends _i1.Mock implements _i18.PlantJournalUseCases {
  MockPlantJournalUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.PlantJournalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePlantJournalRepository_5(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i7.PlantJournalRepository);

  @override
  _i10.Future<List<_i8.JournalEntry>> getEntries(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getEntries,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i8.JournalEntry>>.value(<_i8.JournalEntry>[]),
      ) as _i10.Future<List<_i8.JournalEntry>>);

  @override
  _i10.Future<_i8.JournalEntry> addEntry(
    _i8.JournalEntry? entry, {
    _i17.File? photoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [entry],
          {#photoFile: photoFile},
        ),
        returnValue: _i10.Future<_i8.JournalEntry>.value(_FakeJournalEntry_6(
          this,
          Invocation.method(
            #addEntry,
            [entry],
            {#photoFile: photoFile},
          ),
        )),
      ) as _i10.Future<_i8.JournalEntry>);

  @override
  _i10.Future<_i8.JournalEntry> updateEntry(
    _i8.JournalEntry? entry, {
    _i17.File? photoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
          {#photoFile: photoFile},
        ),
        returnValue: _i10.Future<_i8.JournalEntry>.value(_FakeJournalEntry_6(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
            {#photoFile: photoFile},
          ),
        )),
      ) as _i10.Future<_i8.JournalEntry>);

  @override
  _i10.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteEntriesForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntriesForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> countEntries(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #countEntries,
          [plantId],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<List<_i8.JournalEntry>> getUnifiedTimeline(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getUnifiedTimeline,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i8.JournalEntry>>.value(<_i8.JournalEntry>[]),
      ) as _i10.Future<List<_i8.JournalEntry>>);

  @override
  _i10.Future<_i8.JournalEntry?> getLatestUnifiedEntry(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getLatestUnifiedEntry,
          [plantId],
        ),
        returnValue: _i10.Future<_i8.JournalEntry?>.value(),
      ) as _i10.Future<_i8.JournalEntry?>);

  @override
  _i10.Future<List<_i8.JournalEntry>> getAllUnifiedTimeline() => (super.noSuchMethod(
        Invocation.method(
          #getAllUnifiedTimeline,
          [],
        ),
        returnValue: _i10.Future<List<_i8.JournalEntry>>.value(<_i8.JournalEntry>[]),
      ) as _i10.Future<List<_i8.JournalEntry>>);
}
