// Mocks generated by Mockito 5.4.6 from annotations
// in open_plants/test/plant_data_cleanup_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i10;
import 'dart:io' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:open_plants/pages/care_schedule/care_schedule_action.dart' as _i21;
import 'package:open_plants/pages/care_schedule/care_schedule_repository.dart' as _i7;
import 'package:open_plants/pages/care_schedule/care_schedule_usecases.dart' as _i16;
import 'package:open_plants/pages/care_schedule/care_task.dart' as _i17;
import 'package:open_plants/pages/care_schedule/room_config.dart' as _i19;
import 'package:open_plants/pages/care_schedule/schedule_config.dart' as _i18;
import 'package:open_plants/pages/care_schedule/task_completion.dart' as _i20;
import 'package:open_plants/pages/diagnosis/diagnosis_history_usecases.dart' as _i14;
import 'package:open_plants/pages/diagnosis/diagnosis_result_entity.dart' as _i13;
import 'package:open_plants/pages/plant_collection/plant_collection_usecases.dart' as _i8;
import 'package:open_plants/pages/plant_journal/plant_journal_item_entity.dart' as _i3;
import 'package:open_plants/pages/plant_journal/plant_journal_repository.dart' as _i2;
import 'package:open_plants/pages/plant_journal/plant_journal_usecases.dart' as _i9;
import 'package:open_plants/pages/plant_photo_timeline/plant_photo_timeline_item_entity.dart' as _i6;
import 'package:open_plants/pages/plant_photo_timeline/plant_photo_timeline_repository.dart' as _i5;
import 'package:open_plants/pages/plant_photo_timeline/plant_photo_timeline_usecases.dart' as _i15;
import 'package:open_plants/pages/symptom_logger/symptom_logger_item_entity.dart' as _i4;
import 'package:open_plants/pages/symptom_logger/symptom_logger_usecases.dart' as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakePlantJournalRepository_0 extends _i1.SmartFake implements _i2.PlantJournalRepository {
  _FakePlantJournalRepository_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJournalEntry_1 extends _i1.SmartFake implements _i3.JournalEntry {
  _FakeJournalEntry_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSymptomLogEntry_2 extends _i1.SmartFake implements _i4.SymptomLogEntry {
  _FakeSymptomLogEntry_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantPhotoTimelineRepository_3 extends _i1.SmartFake implements _i5.PlantPhotoTimelineRepository {
  _FakePlantPhotoTimelineRepository_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantPhoto_4 extends _i1.SmartFake implements _i6.PlantPhoto {
  _FakePlantPhoto_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCareScheduleRepository_5 extends _i1.SmartFake implements _i7.CareScheduleRepository {
  _FakeCareScheduleRepository_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantCollectionUsecases_6 extends _i1.SmartFake implements _i8.PlantCollectionUsecases {
  _FakePlantCollectionUsecases_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePlantJournalUseCases_7 extends _i1.SmartFake implements _i9.PlantJournalUseCases {
  _FakePlantJournalUseCases_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PlantJournalUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantJournalUseCases extends _i1.Mock implements _i9.PlantJournalUseCases {
  MockPlantJournalUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.PlantJournalRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePlantJournalRepository_0(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i2.PlantJournalRepository);

  @override
  _i10.Future<List<_i3.JournalEntry>> getEntries(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getEntries,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i10.Future<List<_i3.JournalEntry>>);

  @override
  _i10.Future<_i3.JournalEntry> addEntry(
    _i3.JournalEntry? entry, {
    _i11.File? photoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addEntry,
          [entry],
          {#photoFile: photoFile},
        ),
        returnValue: _i10.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #addEntry,
            [entry],
            {#photoFile: photoFile},
          ),
        )),
      ) as _i10.Future<_i3.JournalEntry>);

  @override
  _i10.Future<_i3.JournalEntry> updateEntry(
    _i3.JournalEntry? entry, {
    _i11.File? photoFile,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateEntry,
          [entry],
          {#photoFile: photoFile},
        ),
        returnValue: _i10.Future<_i3.JournalEntry>.value(_FakeJournalEntry_1(
          this,
          Invocation.method(
            #updateEntry,
            [entry],
            {#photoFile: photoFile},
          ),
        )),
      ) as _i10.Future<_i3.JournalEntry>);

  @override
  _i10.Future<void> deleteEntry(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntry,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteEntriesForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntriesForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<int> countEntries(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #countEntries,
          [plantId],
        ),
        returnValue: _i10.Future<int>.value(0),
      ) as _i10.Future<int>);

  @override
  _i10.Future<List<_i3.JournalEntry>> getUnifiedTimeline(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getUnifiedTimeline,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i10.Future<List<_i3.JournalEntry>>);

  @override
  _i10.Future<_i3.JournalEntry?> getLatestUnifiedEntry(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getLatestUnifiedEntry,
          [plantId],
        ),
        returnValue: _i10.Future<_i3.JournalEntry?>.value(),
      ) as _i10.Future<_i3.JournalEntry?>);

  @override
  _i10.Future<List<_i3.JournalEntry>> getAllUnifiedTimeline() => (super.noSuchMethod(
        Invocation.method(
          #getAllUnifiedTimeline,
          [],
        ),
        returnValue: _i10.Future<List<_i3.JournalEntry>>.value(<_i3.JournalEntry>[]),
      ) as _i10.Future<List<_i3.JournalEntry>>);
}

/// A class which mocks [SymptomLoggerUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockSymptomLoggerUseCases extends _i1.Mock implements _i12.SymptomLoggerUseCases {
  MockSymptomLoggerUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<_i4.SymptomLogEntry> logSymptom(_i4.SymptomLogEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #logSymptom,
          [entry],
        ),
        returnValue: _i10.Future<_i4.SymptomLogEntry>.value(_FakeSymptomLogEntry_2(
          this,
          Invocation.method(
            #logSymptom,
            [entry],
          ),
        )),
      ) as _i10.Future<_i4.SymptomLogEntry>);

  @override
  _i10.Future<List<_i4.SymptomLogEntry>> getSymptomHistory(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getSymptomHistory,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i4.SymptomLogEntry>>.value(<_i4.SymptomLogEntry>[]),
      ) as _i10.Future<List<_i4.SymptomLogEntry>>);

  @override
  _i10.Future<List<_i4.SymptomLogEntry>> getAllSymptoms() => (super.noSuchMethod(
        Invocation.method(
          #getAllSymptoms,
          [],
        ),
        returnValue: _i10.Future<List<_i4.SymptomLogEntry>>.value(<_i4.SymptomLogEntry>[]),
      ) as _i10.Future<List<_i4.SymptomLogEntry>>);

  @override
  _i10.Future<void> markResolved(String? entryId) => (super.noSuchMethod(
        Invocation.method(
          #markResolved,
          [entryId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> updateSymptom(_i4.SymptomLogEntry? entry) => (super.noSuchMethod(
        Invocation.method(
          #updateSymptom,
          [entry],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> saveDraft(
    String? plantId,
    Map<String, dynamic>? draft,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveDraft,
          [
            plantId,
            draft,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<Map<String, dynamic>?> getDraft(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getDraft,
          [plantId],
        ),
        returnValue: _i10.Future<Map<String, dynamic>?>.value(),
      ) as _i10.Future<Map<String, dynamic>?>);

  @override
  _i10.Future<void> deleteDraft(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteDraft,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteEntriesForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteEntriesForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<_i13.DiagnosisResultEntity?> getLatestDiagnosis(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getLatestDiagnosis,
          [plantId],
        ),
        returnValue: _i10.Future<_i13.DiagnosisResultEntity?>.value(),
      ) as _i10.Future<_i13.DiagnosisResultEntity?>);
}

/// A class which mocks [DiagnosisHistoryUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockDiagnosisHistoryUseCases extends _i1.Mock implements _i14.DiagnosisHistoryUseCases {
  MockDiagnosisHistoryUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i10.Future<List<_i13.DiagnosisResultEntity>> getAllResults() => (super.noSuchMethod(
        Invocation.method(
          #getAllResults,
          [],
        ),
        returnValue: _i10.Future<List<_i13.DiagnosisResultEntity>>.value(<_i13.DiagnosisResultEntity>[]),
      ) as _i10.Future<List<_i13.DiagnosisResultEntity>>);

  @override
  _i10.Future<List<_i13.DiagnosisResultEntity>> getResultsForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getResultsForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i13.DiagnosisResultEntity>>.value(<_i13.DiagnosisResultEntity>[]),
      ) as _i10.Future<List<_i13.DiagnosisResultEntity>>);

  @override
  _i10.Future<void> deleteResult(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteResult,
          [id],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteResultsForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteResultsForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [PlantPhotoTimelineUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantPhotoTimelineUseCases extends _i1.Mock implements _i15.PlantPhotoTimelineUseCases {
  MockPlantPhotoTimelineUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.PlantPhotoTimelineRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakePlantPhotoTimelineRepository_3(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i5.PlantPhotoTimelineRepository);

  @override
  _i10.Future<_i6.PlantPhoto> addPhoto(
    String? plantId,
    _i11.File? image, {
    DateTime? date,
    String? caption,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPhoto,
          [
            plantId,
            image,
          ],
          {
            #date: date,
            #caption: caption,
          },
        ),
        returnValue: _i10.Future<_i6.PlantPhoto>.value(_FakePlantPhoto_4(
          this,
          Invocation.method(
            #addPhoto,
            [
              plantId,
              image,
            ],
            {
              #date: date,
              #caption: caption,
            },
          ),
        )),
      ) as _i10.Future<_i6.PlantPhoto>);

  @override
  _i10.Future<void> deletePhoto(
    String? plantId,
    String? photoId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deletePhoto,
          [
            plantId,
            photoId,
          ],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<List<_i6.PlantPhoto>> getTimeline(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getTimeline,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i6.PlantPhoto>>.value(<_i6.PlantPhoto>[]),
      ) as _i10.Future<List<_i6.PlantPhoto>>);

  @override
  _i10.Future<List<_i6.PlantPhoto>> updatePhotoDate(
    String? plantId,
    String? photoId,
    DateTime? newDate,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhotoDate,
          [
            plantId,
            photoId,
            newDate,
          ],
        ),
        returnValue: _i10.Future<List<_i6.PlantPhoto>>.value(<_i6.PlantPhoto>[]),
      ) as _i10.Future<List<_i6.PlantPhoto>>);

  @override
  _i10.Future<void> deleteAllPhotos(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllPhotos,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}

/// A class which mocks [CareScheduleUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockCareScheduleUsecases extends _i1.Mock implements _i16.CareScheduleUsecases {
  MockCareScheduleUsecases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.CareScheduleRepository get repository => (super.noSuchMethod(
        Invocation.getter(#repository),
        returnValue: _FakeCareScheduleRepository_5(
          this,
          Invocation.getter(#repository),
        ),
      ) as _i7.CareScheduleRepository);

  @override
  _i8.PlantCollectionUsecases get plantCollection => (super.noSuchMethod(
        Invocation.getter(#plantCollection),
        returnValue: _FakePlantCollectionUsecases_6(
          this,
          Invocation.getter(#plantCollection),
        ),
      ) as _i8.PlantCollectionUsecases);

  @override
  _i9.PlantJournalUseCases get plantJournal => (super.noSuchMethod(
        Invocation.getter(#plantJournal),
        returnValue: _FakePlantJournalUseCases_7(
          this,
          Invocation.getter(#plantJournal),
        ),
      ) as _i9.PlantJournalUseCases);

  @override
  _i10.Future<
      ({
        List<_i17.CareTask> completedEarly,
        Map<String, ({String environment, String name})> roomContext,
        List<_i17.CareTask> tasks
      })> getSchedule() => (super.noSuchMethod(
        Invocation.method(
          #getSchedule,
          [],
        ),
        returnValue: _i10.Future<
            ({
              List<_i17.CareTask> completedEarly,
              Map<String, ({String environment, String name})> roomContext,
              List<_i17.CareTask> tasks
            })>.value((
          completedEarly: <_i17.CareTask>[],
          roomContext: <String, ({String environment, String name})>{},
          tasks: <_i17.CareTask>[]
        )),
      ) as _i10.Future<
          ({
            List<_i17.CareTask> completedEarly,
            Map<String, ({String environment, String name})> roomContext,
            List<_i17.CareTask> tasks
          })>);

  @override
  _i10.Future<List<_i17.CareTask>> completeTask({
    required _i17.CareTask? task,
    String? note,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #completeTask,
          [],
          {
            #task: task,
            #note: note,
          },
        ),
        returnValue: _i10.Future<List<_i17.CareTask>>.value(<_i17.CareTask>[]),
      ) as _i10.Future<List<_i17.CareTask>>);

  @override
  _i10.Future<List<_i17.CareTask>> snoozeTask({
    required _i17.CareTask? task,
    required int? days,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #snoozeTask,
          [],
          {
            #task: task,
            #days: days,
          },
        ),
        returnValue: _i10.Future<List<_i17.CareTask>>.value(<_i17.CareTask>[]),
      ) as _i10.Future<List<_i17.CareTask>>);

  @override
  _i10.Future<List<_i17.CareTask>> skipTask({required _i17.CareTask? task}) => (super.noSuchMethod(
        Invocation.method(
          #skipTask,
          [],
          {#task: task},
        ),
        returnValue: _i10.Future<List<_i17.CareTask>>.value(<_i17.CareTask>[]),
      ) as _i10.Future<List<_i17.CareTask>>);

  @override
  _i10.Future<List<_i17.CareTask>> updateScheduleConfig({
    required String? plantId,
    required _i18.ScheduleConfig? config,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateScheduleConfig,
          [],
          {
            #plantId: plantId,
            #config: config,
          },
        ),
        returnValue: _i10.Future<List<_i17.CareTask>>.value(<_i17.CareTask>[]),
      ) as _i10.Future<List<_i17.CareTask>>);

  @override
  _i10.Future<List<_i17.CareTask>> updateRoomConfig({required _i19.RoomConfig? config}) => (super.noSuchMethod(
        Invocation.method(
          #updateRoomConfig,
          [],
          {#config: config},
        ),
        returnValue: _i10.Future<List<_i17.CareTask>>.value(<_i17.CareTask>[]),
      ) as _i10.Future<List<_i17.CareTask>>);

  @override
  _i10.Future<List<_i20.TaskCompletion>> getTaskHistory(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #getTaskHistory,
          [plantId],
        ),
        returnValue: _i10.Future<List<_i20.TaskCompletion>>.value(<_i20.TaskCompletion>[]),
      ) as _i10.Future<List<_i20.TaskCompletion>>);

  @override
  _i10.Future<List<_i20.TaskCompletion>> getTaskHistoryFiltered({
    required String? plantId,
    String? taskTypeKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaskHistoryFiltered,
          [],
          {
            #plantId: plantId,
            #taskTypeKey: taskTypeKey,
          },
        ),
        returnValue: _i10.Future<List<_i20.TaskCompletion>>.value(<_i20.TaskCompletion>[]),
      ) as _i10.Future<List<_i20.TaskCompletion>>);

  @override
  _i10.Future<List<_i17.CareTask>> deleteCompletion({required _i20.TaskCompletion? completion}) => (super.noSuchMethod(
        Invocation.method(
          #deleteCompletion,
          [],
          {#completion: completion},
        ),
        returnValue: _i10.Future<List<_i17.CareTask>>.value(<_i17.CareTask>[]),
      ) as _i10.Future<List<_i17.CareTask>>);

  @override
  _i10.Future<Map<String, _i21.CareScheduleAction>> getScheduleActions() => (super.noSuchMethod(
        Invocation.method(
          #getScheduleActions,
          [],
        ),
        returnValue: _i10.Future<Map<String, _i21.CareScheduleAction>>.value(<String, _i21.CareScheduleAction>{}),
      ) as _i10.Future<Map<String, _i21.CareScheduleAction>>);

  @override
  _i10.Future<void> deleteCompletionsForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCompletionsForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteCustomRulesForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteCustomRulesForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);

  @override
  _i10.Future<void> deleteAllScheduleActionsForPlant(String? plantId) => (super.noSuchMethod(
        Invocation.method(
          #deleteAllScheduleActionsForPlant,
          [plantId],
        ),
        returnValue: _i10.Future<void>.value(),
        returnValueForMissingStub: _i10.Future<void>.value(),
      ) as _i10.Future<void>);
}
