// Mocks generated by Mockito 5.4.6 from annotations
// in open_plants/test/plant_collection_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:open_plants/pages/plant_collection/plant_collection_datasource.dart' as _i2;
import 'package:open_plants/pages/plant_collection/plant_collection_item_entity.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [PlantCollectionDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlantCollectionDataSource extends _i1.Mock implements _i2.PlantCollectionDataSource {
  MockPlantCollectionDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isBlocked => (super.noSuchMethod(
        Invocation.getter(#isBlocked),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Future<List<_i4.PlantEntity>> loadPlants() => (super.noSuchMethod(
        Invocation.method(
          #loadPlants,
          [],
        ),
        returnValue: _i3.Future<List<_i4.PlantEntity>>.value(<_i4.PlantEntity>[]),
      ) as _i3.Future<List<_i4.PlantEntity>>);

  @override
  _i3.Future<void> savePlants(List<_i4.PlantEntity>? plants) => (super.noSuchMethod(
        Invocation.method(
          #savePlants,
          [plants],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addPlant(_i4.PlantEntity? plant) => (super.noSuchMethod(
        Invocation.method(
          #addPlant,
          [plant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updatePlant(_i4.PlantEntity? plant) => (super.noSuchMethod(
        Invocation.method(
          #updatePlant,
          [plant],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deletePlant(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePlant,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> savePhoto(
    _i5.File? sourceFile,
    String? plantId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #savePhoto,
          [
            sourceFile,
            plantId,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #savePhoto,
            [
              sourceFile,
              plantId,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> deletePhoto(String? photoPath) => (super.noSuchMethod(
        Invocation.method(
          #deletePhoto,
          [photoPath],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
